---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - cd packages/core
  - npm install
  - cd ../elements
  - npm install
  - cd ../esw-fcm
  - npm install
  - cd ../utils
  - npm install
  - cd ../../

install:
  - cd apps/main
  - npm install
  - cd ../widget
  - npm install
  - cd ../

script:
  - cd main
  # - npm run lint:js
  # - npm test
  - cd ../widget
  - npm run lint:js
  - npm test
