---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - cd packages/core
  - npm install
  - cd ../elements
  - npm install
  - cd ../../

install:
  - cd apps/comments
  - npm install
  - cd ../main
  - npm install
  - cd ../../

script:
  - cd apps/comments
  - npm run lint:js
  - npm test
  - cd ../main
  - npm run lint:js
  - npm test
